# Generated by Django 5.0.1 on 2024-01-29 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gokart', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
