# Generated by Django 5.0.1 on 2024-01-30 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gokart', '0005_brand_alter_category_category_image_product_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.CharField(max_length=5, primary_key=True, serialize=False),
        ),
    ]
