# Generated by Django 5.0.1 on 2024-01-30 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gokart', '0009_customeraddress'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerAddress',
        ),
        migrations.DeleteModel(
            name='UserRegistration',
        ),
    ]
