# Generated by Django 5.0.1 on 2024-02-02 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gokart', '0012_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
