# Generated by Django 5.0.1 on 2024-02-05 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gokart', '0020_alter_payment_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.IntegerField(null=True),
        ),
    ]
