# Generated by Django 5.0.1 on 2024-02-05 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gokart', '0021_alter_payment_amount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderPlaced',
        ),
    ]
