# Generated by Django 5.0 on 2024-03-04 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gokart', '0027_alter_orderplaced_status_alter_wishlistitem_added_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplaced',
            name='payment1',
            field=models.CharField(choices=[('COD', 'Cash on Delivery'), ('RazorPay', 'RazorPay')], default='COD', max_length=100),
        ),
    ]
