# Generated by Django 5.0 on 2024-03-11 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gokart', '0028_orderplaced_payment1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderplaced',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='orderplaced',
            name='payment1',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
