# Generated by Django 5.0 on 2024-03-11 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gokart', '0029_remove_orderplaced_payment_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderPlaced',
        ),
    ]
