# Generated by Django 5.0 on 2024-03-24 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gokart', '0033_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderPlaced',
        ),
    ]
